LEGAL_SIMPLIFICATION_RULES = {

    # Modal verbs and obligations
    "shall": "must",
    "shall be": "will be",
    "shall not": "must not",
    "will not be liable": "will not be responsible",
    "is obligated to": "must",
    "is required to": "must",

    # Reference terms
    "hereinafter referred to as": "called",
    "hereinafter referred to": "called",
    "herein": "in this document",
    "hereof": "of this document",
    "hereto": "to this document",
    "heretofore": "before now",
    "thereof": "of that",
    "therein": "in that",
    "thereafter": "after that",
    "therewith": "with that",

    # Legal structure phrases
    "in consideration of": "because of",
    "subject to the provisions of": "according to",
    "subject to": "depending on",
    "pursuant to": "under",
    "in accordance with": "according to",
    "in the event that": "if",
    "for the purpose of": "to",
    "prior to": "before",
    "subsequent to": "after",
    "with respect to": "about",
    "in relation to": "about",
    "in connection with": "related to",
    "at such time as": "when",
    "until such time as": "until",

    # Formal legal phrases
    "notwithstanding": "even if",
    "notwithstanding anything contained herein": "even if something here says otherwise",
    "irrevocably submit": "agree",
    "deemed to": "considered",
    "as may be": "as",
    "whatsoever": "at all",
    "without limitation": "including",
    "including but not limited to": "including",

    # Duties and responsibilities
    "abide by": "follow",
    "devote full time, attention and energies": "work fully",
    "use all reasonable endeavours": "try",
    "best endeavours": "best efforts",
    "perform his duties": "do his job",
    "discharge his duties": "do his responsibilities",

    # Employment-related
    "remuneration": "salary",
    "compensation": "pay",
    "terminate employment": "end the job",
    "termination of employment": "job ending",
    "probation": "trial period",
    "notice period": "notice time",
    "position": "job",
    "engaged in the business": "working in",
    "devote his working time": "spend his work time",

    # Confidentiality & IP
    "confidential information": "private information",
    "proprietary information": "company-owned information",
    "trade secrets": "secret business information",
    "intellectual property": "company creations",
    "know-how": "technical knowledge",
    "non-disclosure": "confidentiality",
    "non-compete": "no-competition",
    "source code": "software code",

    # Liability and indemnity
    "indemnify": "pay for losses",
    "indemnify and hold harmless": "pay for any losses",
    "liable for": "responsible for",
    "without prejudice to": "without affecting",
    "at its own expense": "using its own money",

    # Termination and notice
    "prior written notice": "written notice",
    "with immediate effect": "immediately",
    "termination of this agreement": "ending this agreement",
    "upon termination": "when the agreement ends",
    "cease": "stop",

    # Legal remedies
    "injunctive relief": "court order",
    "irreparable harm": "serious damage",
    "adequate remedy at law": "legal solution",
    "specific performance": "court-ordered action",
    
    "wellin": "",
"wellins": "",
"needtan": "",
"200ren": "200",
"day season": "",
"first activities": "activities",
"generators may claim": "may claim",
"fail her own available": "failed to provide",
"plenty very": "many",
"passing": "processing",
"programsA": "programs",
"process need": "process",
"usuallying": "usually",
"law usuallying": "law usually",

    # Governance and jurisdiction
    "governed by the laws of": "under the laws of",
    "exclusive jurisdiction": "only courts in",
    "settled through arbitration": "resolved by arbitration",
    "venue of arbitration": "place of arbitration",

    # Corporate/legal entities
    "successors and assigns": "future owners or representatives",
    "party of the one part": "first party",
    "party of the other part": "second party",
    "legal entity": "organization",

    # Financial/legal terms
    "per annum": "per year",
    "hereby acknowledges": "confirms",
    "forthwith": "immediately",
    "aforementioned": "mentioned earlier",
    "inter alia": "among others",
    "ab initio": "from the start",

    # General simplifications
    "commence": "start",
    "terminate": "end",
    "execute": "sign",
    "endeavor": "try",
    "facilitate": "help",
    "utilize": "use",
    "obligated": "required",
    "assist": "help",
    "retain": "keep",
    "deem": "consider",
    "convey": "send",
    "request": "ask",
    "obtain": "get",
    "sufficient": "enough",
    "approximately": "about",
    "in the absence of": "without",
    "prior approval": "approval first",
    "subsequently": "later",
    
    "shall refrain from disclosing": "must not share",
    "shall protect the confidentiality": "must keep private",
    "shall remain the property of": "will still belong to",
    "may not be copied or reproduced": "cannot be copied",
    "prior written consent": "written permission",
    "return or destroy": "give back or delete",
    "on a need-to-know basis": "only if required for work",
    "independently developed": "created separately",
    "without restriction": "without limits",
    "legal process": "court order",
    "injunctive relief": "court order to stop the action",
    "specific performance": "court order to fulfill the promise",
    "exclusive jurisdiction": "only these courts can decide",
    "binding agreement": "official contract",
    "principal-to-principal basis": "independent relationship",
    "governed by the laws of": "subject to the laws of",
    "shall survive termination": "will continue after the agreement ends",
    "irrevocably submit": "agree without the right to refuse",
    "counterparts": "separate signed copies",
}
